on: [push]

# TODO: maybe make reusable workflow?

jobs:
  wuphf_push_notification:
    runs-on: ubuntu-latest
    name: send WUPHF notifications on push
    steps:
      - name: wuphf_push_notification
        uses: cstuder/apprise-ga@master
        with:
          title: "Push received on {{ ref }}"
          message: "Commit by {{ head_commit.author.name }}: {{ head_commit.message | truncate(128) }} ({{ head_commit.id[0:7] }})"
        env:
          APPRISE_URL: ${{ secrets.APPRISE_URL }}
