on: [push]

jobs:
  wuphf_push_notification:
    strategy:
      matrix:
        service: [
          APPRISE_SLACK, 
          APPRISE_DISCORD, 
          APPRISE_TELEGRAM, 
          APPRISE_EMAIL,
          APPRISE_SMS, 
          APPRISE_WEBHOOK, 
          APPRISE_PUSHOVER, 
          APPRISE_TWILIO, 
          APPRISE_HIPCHAT, 
          APPRISE_MSTEAMS, 
        ]
    env:
      apprise-url: ${{secrets[matrix.service]}}

    runs-on: ubuntu-latest

    steps:
      - run: echo ${{matrix.service}}
      - run: echo ${{ env.apprise-url }} | base64
      - name: wuphf_push_notification
        uses: cstuder/apprise-ga@master
        with:
          title: "Push received on {{ ref }} "
          message: "Commit by {{ head_commit.author.name }}: {{ head_commit.message | truncate(128) }} ({{ head_commit.id[0:7] }})"
        env:
          APPRISE_URL: ${{ env.apprise-url }}

