on: [push]

jobs:
  wuphf_push_notification:
    strategy:
      matrix:
        static: [10, 12, 14]
    runs-on: ubuntu-latest

    steps:
      - run: 'echo "Static matrix: ${{ matrix.static }}"'

#    name: send WUPHF notifications on push
#    steps:
#      - name: wuphf_push_notification
#        uses: cstuder/apprise-ga@master
#        with:
#          title: "Push received on {{ ref }} "
#          message: "Commit by {{ head_commit.author.name }}: {{ head_commit.message | truncate(128) }} ({{ head_commit.id[0:7] }})"
#        env:
#          APPRISE_URL: ${{ matrix.apprise-url }}

 # ------------------------
  say_hello:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.generate-matrix.outputs.services }}
    steps:
      - name: Generate Matrix
        id: generate-matrix
        run: |
          SERVICES='${{ toJSON(secrets.EMIEL_STINKT) }}'
          echo ::set-output name=services::${SERVICES}
  # ------------------------
  my_echo:
    runs-on: ubuntu-latest
    needs:
      - say_hello
    steps:
      - name: Echo previous outputs
        run: echo "${{ toJSON(needs.say_hello.outputs) }}"
  # ------------------------
  my_matrix:
    runs-on: ubuntu-latest
    needs:
      - my_echo
      - say_hello
    strategy:
      matrix:
        service: ${{ fromJSON(needs.say_hello.outputs.services) }}
    steps:
      - name: Matrix => (${{ matrix.service }})
        run: |
          echo ${{ matrix.service }}